name: Generate Diagram

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate codebase visualization
        uses: githubocto/repo-visualizer@main

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add diagram.svg
          git commit -m "Update codebase visualization"
          git push
